### ISSUE TITLE
Dynamic customization using 'parameters transformers' failed to deploy backing application results in error 'null'

### ISSUE THREAD

**Issue by buddyavis** [spring-cloud/spring-cloud-app-broker#319]
**Given** parameters transformers are configured to dynamically customize service instance parameters to modify any aspect of the backing application deployment(properties, environment variables, services, etc.)

parameters-transformers:
  -name: PropertyMapping
     args:
           - include: count,memory,host,domain

**When** user provides parameters while creating a service instance {count=1, memory='1G', host='psg-canary-dev1', domain='cfapps-gt1-dev.nam.nsroot.net'},

**Then** service instance backing application should be deployed with the user provided parameter values,

**And** service instance should be created.

However backing app deployment failed with log details error in deploying backing applications for the selected service/plan with error 'null'

**Comment by Albertoimpl** [comment]
Thanks a lot of submitting an issue @buddyavis.
There are a few test examples that cover the case you are showing: 

https://github.com/spring-cloud/spring-cloud-app-broker/blob/master/spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/CreateInstanceWithParametersAcceptanceTest.java

https://github.com/spring-cloud/spring-cloud-app-broker/blob/master/spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/CreateInstanceWithServicesParametersComponentTest.java

Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can reproduce the issue?

Also, could you provide a debug trace so that we see what happened?

Thanks!

**Comment by buddyavis** [comment]
It’s working fine with my own custom implementation, extending spring cloud app broker workflow instances and implemented my own parameter transformer by extending ParameterTransformerFactory. Unfortunately I cannot upload any code or files as per my organization policy. Thanks a lot.
