### ISSUE TITLE
Usage of raw Environment Variables

### ISSUE THREAD

**Issue by PG2000** [spring-cloud/spring-cloud-app-broker#442]
Hello,

i'm missing the capability to set an environment variable for the Backing Application.

I would like to see the Variable: 
JBP_CONFIG_OPEN_JDK_JRE="{ jre: { version: 11.+ } }" inside the app

Instead the variable is put into SPRING_APPLICATION_JSON={} 
and it's not possible to deploy the Backing Application with JAVA11 on Cloud Foundry.

Am i missing something?

**Comment by spikymonkey** [comment]
You can set the `use-spring-application-json` [property](https://docs.spring.io/spring-cloud-app-broker/docs/1.3.0/reference/#properties-configuration) to `false` in order to use raw environment variables. Sorry, this setting seems to be missing from our docs. We could probably handle this better too, making sure any java buildpack vars remain in the environment even if `use-spring-application-json` is `true`.
